### ISSUE TITLE
Build fails on Windows 10 Home ESX 5.5 VM

### ISSUE THREAD

**Issue by KipRepscher** [Microsoft/ProtocolTestFramework#18]
After installing prerequisites and rebooting the host, the following error message is produced while running "build.cmd formodel":

C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix2010.targets(772,5): error MSB4062: The "ResolveWixReferences" task could not be loaded from the assembly C:\Program Files (x86)\WiX Toolset v3.10\bin\WixTasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft
.Build.Framework.ITask. [C:\Users\test\protocoltestframework\src\deploy\Installer\ProtocolTestFrameworkInstaller.wixproj]
Done Building Project "C:\Users\test\protocoltestframework\src\deploy\Installer\ProtocolTestFrameworkInstaller.wixproj"
 (Clean;Rebuild target(s)) -- FAILED.

The same error is produced without the "formodel" argument.

Please let me know if you need any other information.
Attached a log of the failed build.

[buildFail.txt](https://github.com/Microsoft/ProtocolTestFramework/files/543205/buildFail.txt)

**Comment by yazeng** [comment]
Hi Kip,
Thanks for the feedback.
It looks like a bug of Wix toolset. I searched the error and found this: 
https://github.com/wixtoolset/issues/issues/5291
What version of wix tool did you install? Is it 3.10.3.2094? If so, could you change it to another version?

Btw, you can get our built msi here, instead of building it by yourself:
https://github.com/Microsoft/ProtocolTestFramework/releases

Thanks,
Yan

**Comment by KipRepscher** [comment]
WiX Toolset v3.10.2.2516 is currently installed.

Thanks for the link to the msi file.  I'm moving ahead with that.

**Comment by BerndBunk** [comment]
I observe the same problem since a few days with WiX v3.10.1124.0 and VS2012, VS2013 and VS2015 on several different VMs! (all broke at the same time^^)
I uninstalled and switched to WiX v3.10.3.3007 (latest stable), but this did not change anything.
This got broken a few days ago without me changing any source code or anything in Visual Studio.
The only thing I changed was that I installed the latest Windows Update on these VMs. Maybe one of the patches changed some WiX dependencies!?

**Comment by yazeng** [comment]
I'm using wix 3.10.1.2213 and it works fine.
And I'm using Windows 10 with latest Windows update.
So @BerndBunk , do you mean it worked before and suddenly some day it stopped working?

**Comment by BerndBunk** [comment]
> So @BerndBunk<https://github.com/BerndBunk> , do you mean it worked before and suddenly some day it stopped working?
Yes, that’s exactly what I mean.
On several VMs with different VS versions, but same Win 10 installation all WiX projects stopped compiling 10 days ago.
That’s why I believe it has something to do with the Windows Update.

I just reverted one VM back to state 2 month ago, and the same WiX projects now compile again!
Next week I will investigate which Windows Update caused the problem and post my results.
I remember that beginning of this month there was one huge update for Windows 10… that is maybe a good candidate to look at.

Of course it might be that I have a general setting bug in my WiX projects or its installation, that only in combination with VM, Win 10 and the latest update causes the problem!?
But I don’t know that yet…

Happy Halloween,
Bernd

**Comment by mishra14** [comment]
🔔

**Comment by yazeng** [comment]
Close this issue since we don't not have further discussion on it.
