### ISSUE TITLE
The value of NTFS_ShareFolder is empty

### ISSUE THREAD

**Issue by dilipcnaik** [microsoft/ProtocolTestFramework#33]
I am running the BVT tests against my private SMB 3 server implementation. I see multiple failures with "xxxx is incocnlusive. The value of NTFS_SHareFolder" is empty...."

If I carefully read the user guide, the 6 shares I need to create on the SUT are named FileShare, SMBBasic, SameWithSMBBasic, DifferentFromSMBBasic, ShareForceLevel2, SMBEncrypted. 

Which one of these is "NTFS_SHareFolder"? 

Am I expected to create files in "NTFS_SHareFolder"? 

Please clarify what is failing when I see the message "NTFS_SHareFoler is empty"

Thank you

**Comment by yazeng** [comment]
Hi Dillip,

The default value of "NTFS_ShareFolder" is “FileShare”.
Besides creating the file share on SUT, you need to make sure the value of the property “NTFS_ShareFolder” is not empty.
Are you using Protocol Test Manager (PTM) or ptfconfig file directly? If you are using PTM to run the test cases, please go to the page below and check its value.
 
![issue33](https://user-images.githubusercontent.com/10937464/86311292-a5030480-bc52-11ea-9652-b520a9917497.png)


Btw, since it’s related to test suite configuration, we’d like to suggest you to file issues in the repo [Windows Protocol Test Suite](https://github.com/microsoft/WindowsProtocolTestSuites) next time.

Thanks,
Yan
Windows Protocol Test Suites Development Team

**Comment by dilipcnaik** [comment]
Thx! Appreciate the quick response

Will do on proper issue filing 

Please excuse typos - sent from a mobile device
